excerpt_separator: ""
pygments: true
markdown: kramdown
title: My Take
tagline: Writing Practice
description: My awesome new site via <a href="https://tinypress.co/&quot; target=&quot;_blank">Tinypress</a>
paginate: 5