excerpt_separator: ""
pygments: true
markdown: kramdown
title: Not So SmartGWT
tagline: Latest in SmartGWT Annoyances
description: My awesome new site via <a href="https://tinypress.co/&quot; target=&quot;_blank">Tinypress</a>
paginate: 5
