excerpt_separator: ""
pygments: true
markdown: kramdown
title: Not So Smart GWT
tagline: Latest in  Smart GWT Annoyances
description: A little blog experiment using <a href="https://pages.github.com/">GitHub Pages</a> processed by <a href="https://tinypress.co/&quot; target=&quot;_blank">Tinypress</a>
paginate: 5
